/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.github.mikan.tart.core.network.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param identities メンバーのユーザーIDかチームに登録しているemailアドレスの一覧
 */


data class AddGroupMemberRequest (

    /* メンバーのユーザーIDかチームに登録しているemailアドレスの一覧 */
    @Json(name = "identities")
    val identities: kotlin.collections.List<kotlin.String>

) {


}

