/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.github.mikan.tart.core.network.model

import io.github.mikan.tart.core.network.model.User

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 記事やプロジェクトに付けられたコメントを表します。プロジェクトへのコメントはQiita Teamでのみ有効です。
 *
 * @param body コメントの内容を表すMarkdown形式の文字列
 * @param createdAt データが作成された日時
 * @param id コメントの一意なID
 * @param renderedBody コメントの内容を表すHTML形式の文字列
 * @param updatedAt データが最後に更新された日時
 * @param user 
 */


data class Comment (

    /* コメントの内容を表すMarkdown形式の文字列 */
    @Json(name = "body")
    val body: kotlin.String,

    /* データが作成された日時 */
    @Json(name = "created_at")
    val createdAt: kotlin.String,

    /* コメントの一意なID */
    @Json(name = "id")
    val id: kotlin.String,

    /* コメントの内容を表すHTML形式の文字列 */
    @Json(name = "rendered_body")
    val renderedBody: kotlin.String,

    /* データが最後に更新された日時 */
    @Json(name = "updated_at")
    val updatedAt: kotlin.String,

    @Json(name = "user")
    val user: User

) {


}

