/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.github.mikan.tart.core.network.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param urlName グループのチーム上での一意な名前を表します。
 * @param name グループに付けられた表示用の名前を表します。
 * @param `private` 非公開グループかどうかを表します。
 * @param description Qiita Teamのグループを表します。
 */


data class CreateGroupRequest (

    /* グループのチーム上での一意な名前を表します。 */
    @Json(name = "url_name")
    val urlName: kotlin.String,

    /* グループに付けられた表示用の名前を表します。 */
    @Json(name = "name")
    val name: kotlin.String,

    /* 非公開グループかどうかを表します。 */
    @Json(name = "private")
    val `private`: kotlin.Boolean,

    /* Qiita Teamのグループを表します。 */
    @Json(name = "description")
    val description: kotlin.String? = null

) {


}

