/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.github.mikan.tart.core.network.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param createdAt 
 * @param description 
 * @param name 
 * @param `private` 
 * @param updatedAt 
 * @param urlName 
 */


data class GetAuthenticatedUserItemsResponseInnerGroup (

    @Json(name = "created_at")
    val createdAt: kotlin.String? = null,

    @Json(name = "description")
    val description: kotlin.String? = null,

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "private")
    val `private`: kotlin.Boolean? = null,

    @Json(name = "updated_at")
    val updatedAt: kotlin.String? = null,

    @Json(name = "url_name")
    val urlName: kotlin.String? = null

) {


}

