/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.github.mikan.tart.core.network.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param description 
 * @param facebookId 
 * @param followeesCount 
 * @param followersCount 
 * @param githubLoginName 
 * @param id 
 * @param itemsCount 
 * @param linkedinId 
 * @param location 
 * @param name 
 * @param organization 
 * @param permanentId 
 * @param profileImageUrl 
 * @param teamOnly 
 * @param twitterScreenName 
 * @param websiteUrl 
 */


data class GetAuthenticatedUserItemsResponseInnerUser (

    @Json(name = "description")
    val description: kotlin.String? = null,

    @Json(name = "facebook_id")
    val facebookId: kotlin.String? = null,

    @Json(name = "followees_count")
    val followeesCount: kotlin.Int? = null,

    @Json(name = "followers_count")
    val followersCount: kotlin.Int? = null,

    @Json(name = "github_login_name")
    val githubLoginName: kotlin.String? = null,

    @Json(name = "id")
    val id: kotlin.String? = null,

    @Json(name = "items_count")
    val itemsCount: kotlin.Int? = null,

    @Json(name = "linkedin_id")
    val linkedinId: kotlin.String? = null,

    @Json(name = "location")
    val location: kotlin.String? = null,

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "organization")
    val organization: kotlin.String? = null,

    @Json(name = "permanent_id")
    val permanentId: kotlin.Int? = null,

    @Json(name = "profile_image_url")
    val profileImageUrl: kotlin.String? = null,

    @Json(name = "team_only")
    val teamOnly: kotlin.Boolean? = null,

    @Json(name = "twitter_screen_name")
    val twitterScreenName: kotlin.String? = null,

    @Json(name = "website_url")
    val websiteUrl: kotlin.String? = null

) {


}

