/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.github.mikan.tart.core.network.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Qiita Teamのグループのメンバーを表します。
 *
 * @param id ユーザーID
 * @param name チームに登録しているユーザー名
 * @param email メンバーのemailアドレス(チームの管理者かオーナーでなければ空文字が返されます)
 */


data class GroupMember (

    /* ユーザーID */
    @Json(name = "id")
    val id: kotlin.String,

    /* チームに登録しているユーザー名 */
    @Json(name = "name")
    val name: kotlin.String,

    /* メンバーのemailアドレス(チームの管理者かオーナーでなければ空文字が返されます) */
    @Json(name = "email")
    val email: kotlin.String

) {


}

