/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.github.mikan.tart.core.network.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Qiita Teamのグループを表します。
 *
 * @param createdAt データが作成された日時
 * @param description グループの詳細を表します。
 * @param name グループに付けられた表示用の名前を表します。
 * @param `private` 非公開グループかどうかを表します。
 * @param updatedAt データが最後に更新された日時
 * @param urlName グループのチーム上での一意な名前を表します。
 */


data class Group (

    /* データが作成された日時 */
    @Json(name = "created_at")
    val createdAt: kotlin.String,

    /* グループの詳細を表します。 */
    @Json(name = "description")
    val description: kotlin.String,

    /* グループに付けられた表示用の名前を表します。 */
    @Json(name = "name")
    val name: kotlin.String,

    /* 非公開グループかどうかを表します。 */
    @Json(name = "private")
    val `private`: kotlin.Boolean,

    /* データが最後に更新された日時 */
    @Json(name = "updated_at")
    val updatedAt: kotlin.String,

    /* グループのチーム上での一意な名前を表します。 */
    @Json(name = "url_name")
    val urlName: kotlin.String

) {


}

