/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.github.mikan.tart.core.network.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param clientId 登録されたAPIクライアントを特定するためのID
 * @param scopes アクセストークンに許された操作の一覧
 * @param token アクセストークンを表現する文字列
 */


data class IssueAccessTokenResponse (

    /* 登録されたAPIクライアントを特定するためのID */
    @Json(name = "client_id")
    val clientId: kotlin.String,

    /* アクセストークンに許された操作の一覧 */
    @Json(name = "scopes")
    val scopes: kotlin.collections.List<kotlin.String>,

    /* アクセストークンを表現する文字列 */
    @Json(name = "token")
    val token: kotlin.String

) {


}

