/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.github.mikan.tart.core.network.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param clientId 登録されたAPIクライアントを特定するためのID
 * @param clientSecret 登録されたAPIクライアントを認証するための秘密鍵
 * @param code リダイレクト用のURLに付与された、アクセストークンと交換するための文字列
 */


data class IssueAccessTokenRequest (

    /* 登録されたAPIクライアントを特定するためのID */
    @Json(name = "client_id")
    val clientId: kotlin.String,

    /* 登録されたAPIクライアントを認証するための秘密鍵 */
    @Json(name = "client_secret")
    val clientSecret: kotlin.String,

    /* リダイレクト用のURLに付与された、アクセストークンと交換するための文字列 */
    @Json(name = "code")
    val code: kotlin.String

) {


}

